config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :searches

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/search',  :to => 'searches#new'
  match '/results', :to => 'searches#update'
  match '/dl', :to => 'searches#download'

  root              :to => 'searches#new'

end

app/controllers/searches_controller.rb
require 'mechanize'
require 'digest'
require 'uri'
require 'dlc'
require 'active_support/secure_random'
class SearchesController < ApplicationController

  def new
    @title = "Le Leecher"
  end



  def create
    session[:username] = params[:search][:forumuser]
    session[:password] = params[:search][:forumpass]
    session[:query] = params[:search][:forumquery]
    session[:forumchoice] = params[:forumchoice]
    session[:prefixchoice] = params[:prefixchoice]
    session[:dlc] = params[:search][:dlc]

    session[:digest] = Digest::MD5.hexdigest(session[:password])
    agent = Mechanize.new
    dologin(session[:username], session[:password], session[:digest], agent)

    page = agent.get("http://tehparadox.com/forum/search.php")
    gettoken(page)
    
    securitytoken = @token

    if securitytoken != "guest"
      dosearch(session[:query], session[:forumchoice], session[:prefixchoice], securitytoken, agent, page)
      render 'update'
    else
      flash.now[:error] = "Login data was incorrect."
      @title = "Le Leecher"
      render 'new'
    end
  end



  def update
    @threadchoice = params[:search][:threadchoice]
    session[:threadchoice] = @threadchoice
    agent = Mechanize.new
    dologin(session[:username], session[:password], session[:digest], agent)
    @dlc = session[:dlc]
    a = mirror(session[:prefixchoice])

    url = ""
    url = @threadchoice
    URI.parse(url.gsub(/ /, '+'))
    page = agent.get(url)
    @linklist = Array.new
    @links = Array.new
    postBody = page.parser.xpath('/html/body/div[2]/div[3]/div[2]/div/div/table/tr[2]/td[2]/div').map do |row|
      strong = row.to_s
      strong = strong.split(" ")
      i=0
      while (strong[i]!=nil)
        if strong[i] =~ /#{a}/
           line = strong[i].match(/\h([^<]+)/)
           @linklist << line
           @links << line
           @links << " "
        end
        i=i+1
      end
    end
    @links = @links.to_s
    if @dlc != "0"
      @p = DLC::Package.new
      i = 0
      while (@linklist[i]!=nil)
        @p.add_link("#{@linklist[i]}") 
        i = i + 1
      end
      session[:dlcname] = SecureRandom.hex(13) + ".dlc"
      open("tmp/#{session[:dlcname]}","w") do |f|
        f.write @p.dlc
      end
    end
    render 'show'
  end



  def show
    if params[:search][:threadchoice].nil?
      render 'new'
    else
      @title = "Le Leecher Results"
    end
  end



  def download
    @filename ="tmp/#{session[:dlcname]}"
    send_file(@filename, :filename => "#{session[:dlcname]}", :stream => false)
  end



end

app/helpers/searches_helper.rb
require 'mechanize'
require 'digest'
require 'uri'
module SearchesHelper

  def arraymen(width, height)
      a = Array.new(width)
      a.map! { Array.new(height) }
      return a
  end

  def dologin(username, password, digest, agent)
    page = agent.get("http://tehparadox.com/forum/index.php")
    login_form = agent.page.form_with(:action => 'http://tehparadox.com/forum/login.php?do=login')
    login_form['vb_login_username'] = username
    login_form['vb_login_password'] = password
    login_form['vb_login_md5password_utf'] = digest
    login_form['vb_login_md5password'] = digest
    login_form['s'] = ""
    login_form['securitytoken'] = "guest"
    login_form['do'] = "login"
    login_form['cookieuser'] = "1"
    ### Submit the login form ###
    page = agent.submit login_form
  end

  def dosearch(query, forumchoice, prefixchoice, securitytoken, agent, page)
    ### Load the search form ###
    search_form = agent.page.form_with(:action => 'search.php?do=process')
    ### Populate the search form ###
    child = 1
    #system('cls')

    ### Complete search form with data and token ###
    search_form['query'] = query
    search_form['titleonly'] = 1
    search_form['forumchoice[]'] = forumchoice
    search_form['childforums'] = child
    search_form['prefixchoice[]'] = prefixchoice
    search_form['s'] = ""
    search_form['securitytoken'] = securitytoken
    search_form['do'] = "process"
    search_form['searchthreadid'] = ""
    ### submit the search form ###
    page = agent.submit search_form
    
    i=1
    @threadlist = arraymen(50,50)
    @threadlist[0][0] = nil

    page.links.each do |link|
      if link.text.match(/#{query}/i)
      ### Fill the array with the titles and links from the file ###
        @threadlist[i][0] = link.text # scans for thread title
        @threadlist[i][1] = "http://tehparadox.com/forum/#{link.href}"
        i=i+1
      end
    end
    return @threadlist
  end

  def gettoken(page)
      @token = ""
      ### Load the whole page ###
      troll = page.parser.xpath('/html').map do |row|    
        leech = row.text.match(/Sec([^v]+)"/i)
        leech = leech.to_s
        ### Trim the string to just the actual token ###
        @token = leech.scan(/\"([^.]+)\"/).to_s
      end
  end

  def mirror(provider)
    if provider == "MU"
      return "megaupload"
    elsif provider == "RS"
      return "rapidshare"
    elsif provider == "HF"
      return "hotfile"
    elsif provider == "x7"
      return "x7"
    elsif provider == "NL"
      return "netload"
    elsif provider == "MS"
      return "megashares"
    elsif provider == "SM"
      return "filesonic"
    elsif provider == "MF"
      return "mediafire"
    elsif provider == "FF"
      return "filefactory"
    elsif provider == "DL"
      return "duckload"
    elsif provider == "FS"
      return fileserve
    elsif provider == "UL"
      return "uploading"
    elsif provider == "DF"
      return "depositfiles"
    elsif provider == "FTP"
      return //
    elsif provider == "Other"
      return //
    elsif provider == "Multi"
      return //
    elsif provider == ""
      return //
    elsif provider == "-1"
      return //
    end
  end

  def clippy(text, bgcolor='#FFFFFF')
    <<-EOF.html_safe
      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
              width="110"
              height="14"
              id="clippy" >
      <param name="movie" value="/flash/clippy.swf"/>
      <param name="allowScriptAccess" value="always" />
      <param name="quality" value="high" />
      <param name="scale" value="noscale" />
      <param NAME="FlashVars" value="text=#{text}">
      <param name="bgcolor" value="#{bgcolor}">
      <embed src="/flash/clippy.swf"
             width="110"
             height="14"
             name="clippy"
             quality="high"
             allowScriptAccess="always"
             type="application/x-shockwave-flash"
             pluginspage="http://www.macromedia.com/go/getflashplayer"
             FlashVars="text=#{text}"
             bgcolor="#{bgcolor}"
      />
      </object>
    EOF
  end
end

app/views/searches/new.html.erb
<div class = "headerdiv"><p><span class="bigger">WebLeecher</span> Beta v0.4.0</p></div>

<%= form_for(:search, :url => searches_path) do |f| %>
  <div id="searchnewleft">
    <div class="field">
      <%= f.label "Username:" %><br />
      <%= f.text_field :forumuser %>
    </div>

    <div class="field">
      <%= f.label "Password:" %><br />
      <%= f.password_field :forumpass %>
    </div>
    <div class="field">
      <%= f.label "Search Query:" %><br />
      <%= f.text_field :forumquery %>
    </div>

    <div>
    <p id = "troll" >Prefix:</p>
    <%= select_tag :prefixchoice, options_for_select([
        ["[MU] Megaupload", "MU"], ["[RS] Rapidshare", "RS"], ["[HF] Hotfile", "HF"],
        ["[x7] x7", "x7"], ["[NL] Netload", "NL"], ["[MS] Megashares", "MS"], ["[FSn] Filesonic", "SM"], 
        ["[MF] Mediafire", "MF"], ["[FF] Filefactory", "FF"], ["[DL] Duckload", "DL"], 
        ["[FSrv] Fileserve", "FS"], ["[UL] Uploading", "UL"], ["[DF] Depositfiles", "DF"], ["[FTP]", "FTP"], 
        ["[Other]", "Other"], ["[MULTI]", "Multi"], ["(any prefix)", ""], ["(no prefix)", "-1"]]), 
        :class => "prefixchoice", :multiple => false %>
    
    </div>
        <div>
      <%= f.check_box :dlc %> <span class = "smaller"> Generate DLC? </span>
    </div>
  </div>

  <div>
    <p id = "troll2">Category:</p>
    <%= select_tag :forumchoice, options_for_select([
        ["WHOLE SITE", "6"], 
        [" Applications", "51"],[" ---- 0Day Releases", "112"],
        [" Games", "43"], [" ---- Console Games", "76"],   
        [" Anime", "42"], [" ---- Manga", "44"], 
        [" Movies", "56"],[" ---- HD - 720p to 1080p", "89"], [" ---- DVDR", "100"], [" ---- TV Shows", "73"], 
        [" Music", "55"], [" ---- Music Videos", "84"], [" ---- OST", "86"], [" ---- Lossless Audio", "117"], 
        [" Comic Books", "68"], [" ---- 0Day Releases", "91"], [" ---- DC/Wildstorm/Vertigo", "70"], 
        [" ---- Image/TopCow", "71"], [" ---- Dark Horse", "88"], [" ---- Alternative Comic", "72"], 
        [" ---- Crossovers", "87"], 
        [" Ebooks & Tutorials", "58"], [" Web/Design Resources", "75"]]), 
        :class => "forumchoice", :multiple => true %>
    
  </div>
  <div class="actions" id = "Leech">
    <%= f.submit "Leech!", :id => "LeechButton" %>
    <input id = "ResetButton" type="reset" value="Reset all fields">
  </div>

  <!-- To be implemented
  <div id = "childforums">
    <%= f.check_box(:childforums) %>
    <%= f.label("Search in child forums.") %>
  </div>
  -->

<% end %>
<span class="smaller2"><%= version %></span>

app/views/searches/show.html.erb
<div><p><span class="bigger">Results</span></p></div>



<div style = "margin-bottom: -15px; padding-top: 10px;">
  <%= clippy(@links, bgcolor='#E6E6E6') %>
</div>
<span class = "smaller3">Thread link: <%= link_to "Click Here", @threadchoice %></span>
<div class="code-box">
  <% i = 0 %>
  <% while (@linklist[i]!=nil) %>
	<%= "#{@linklist[i]}" %> <br />
    <% i = i + 1 %>
  <% end %>
</div>

<% if @dlc != "0" %>
	<%= form_for(:search, :url => { :action => 'download'}) do |f| %>
		<div class="actions">
			<%= f.submit "Download DLC" %>
		</div>
	<% end %>
<% end %>
<span class="smaller2"><%= version %></span>

app/views/searches/update.html.erb
<div><p><span class="bigger">Pick a thread:</span></p></div>

<%= form_for(:search, :url => { :action => 'update'}) do |f| %>
  <% i = 1 %>
  <% default = true %>
  <% while (@threadlist[i][0]!=nil) %>
    <%= f.radio_button(:threadchoice, "#{@threadlist[i][1]}", { :checked => default }) %>
    <% default = false %>
    <%= f.label(:threadchoice, "#{@threadlist[i][0]}") %> <br />
    <% i = i + 1 %>
  <% end %>
  <div class="actions">
    <%= f.submit "Continue" %>
  </div>
<% end %>

<span class="smaller2"><%= version %></span>